### ISSUE TITLE
使用调度器的问题

### ISSUE THREAD

**Issue by stevenliuit** [vincentruan/quartz-monitor#1]
我看了一下mbeanserver里的属性里 根本没有AllJobDetails 我分别测试了2.2.2、2.2.1、2.0.0、1.8.6、1.8.4都没有发现，用jconsole链接上去了 发现也没有此属性 为啥呢？你用的什么版本

**Comment by vincentruan** [comment]
当时我用的weblogic测试,quartz版本为2.2.x，tomcat应该也是这个

**Comment by stevenliuit** [comment]
oh 我刚才发现了 我用的是低版本的 换了那么多jar 没编译 。。。 但是 1.6.4的quartz里是没有那个东西的

**Comment by vincentruan** [comment]
目前仅支持2.X以上版本

**Comment by stevenliuit** [comment]
oh 那就不怪了……！！！还得改代码……！！！

**Comment by vincentruan** [comment]
Issue was closed since JMX monitor is currently support quartz 2.X
